import AssetEntityField from '/scripts/core/menu/input/AssetEntityField.js';
import AudioField from '/scripts/core/menu/input/AudioField.js';
import CheckboxField from '/scripts/core/menu/input/CheckboxField.js';
import ColorField from '/scripts/core/menu/input/ColorField.js';
import CubeImageField from '/scripts/core/menu/input/CubeImageField.js';
import EnumField from '/scripts/core/menu/input/EnumField.js';
import EulerField from '/scripts/core/menu/input/EulerField.js';
import ImageField from '/scripts/core/menu/input/ImageField.js';
import MaterialField from '/scripts/core/menu/input/MaterialField.js';
import MenuField from '/scripts/core/menu/input/MenuField.js';
import NumberField from '/scripts/core/menu/input/NumberField.js';
import TextField from '/scripts/core/menu/input/TextField.js';
import TextureField from '/scripts/core/menu/input/TextureField.js';
import Vector2Field from '/scripts/core/menu/input/Vector2Field.js';
import Vector3Field from '/scripts/core/menu/input/Vector3Field.js';

export { AssetEntityField };
export { AudioField };
export { CheckboxField };
export { ColorField };
export { CubeImageField };
export { EnumField };
export { EulerField };
export { ImageField };
export { MaterialField };
export { MenuField };
export { NumberField };
export { TextField };
export { TextureField };
export { Vector2Field };
export { Vector3Field };

export { AssetEntityField as AssetEntityInput };
export { AudioField as AudioInput };
export { CheckboxField as CheckboxInput };
export { ColorField as ColorInput };
export { CubeImageField as CubeImageInput };
export { EnumField as EnumInput };
export { EulerField as EulerInput };
export { ImageField as ImageInput };
export { MaterialField as MaterialInput };
export { NumberField as NumberInput };
export { TextField as TextInput };
export { TextureField as TextureInput };
export { Vector2Field as Vector2Input };
export { Vector3Field as Vector3Input };
