const PubSubTopics = {
    ASSET_ADDED: "ASSED_ADDED",
    HAND_TOOLS_SWITCH: "HAND_TOOLS_SWITCH",
    INSTANCE_ADDED: "INSTANCE_ADDED",
    INSTANCE_DELETED: "INSTANCE_DELETED",
    INSTANCE_UPDATED: "INSTANCE_UPDATED",
    INSTANCE_ATTACHED: "INSTANCE_ATTACHED",
    INSTANCE_DETACHED: "INSTANCE_DETACHED",
    MATERIAL_ADDED: "MATERIAL_ADDED",
    MATERIAL_DELETED: "MATERIAL_DELETED",
    MATERIAL_UPDATED: "MATERIAL_UPDATED",
    MENU_FIELD_FOCUSED: "MENU_FIELD_FOCUSED",
    MENU_NOTIFICATION: "MENU_NOTIFICATION",
    NOTIFICATION: "NOTIFICATION",
    PROJECT_LOADING: "PROJECT_LOADING",
    PROJECT_SAVING: "PROJECT_SAVING",
    TEXTURE_ADDED: "TEXTURE_ADDED",
    TEXTURE_DELETED: "TEXTURE_DELETED",
    TEXTURE_UPDATED: "TEXTURE_UPDATED",
};

export default PubSubTopics;
