name: CI

on:
  pull_request:
    paths-ignore:
      - 'build/**'
      - 'css/**'
      - 'images/**'
      - 'projects/**'
      - 'resources/**'

permissions:
  contents: read

jobs:
  lint:
    name: Lint testing
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: === Lint testing ===
        run: npm run lint

  test:
    name: Automated Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: === Automated Tests ===
        run: npm test
